ALTER DATABASE base_aa SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO
DBCC CHECKDB(base_aa, REPAIR_REBUILD)
WITH ALL_ERRORMSGS, NO_INFOMSGS
DBCC CHECKDB(base_aa, REPAIR_ALLOW_DATA_LOSS)
WITH ALL_ERRORMSGS, NO_INFOMSGS
ALTER DATABASE base_aa
SET MULTI_USER;
GO
