/** AUTHOR: RUAN ALVES **/

/** BUSCA OS CLIENTES QUE NÃO ESTÃO COM O CEP CORRETO **/
SELECT LEN(CEP) AS QTDE_DIGITOS_CEP, CEP , NOME FROM PESSOA WHERE LEN(CEP) != 8

/** UPDATE NAS PESSOAS QUE ESTÃO COM O CEP INCORRETO **/
UPDATE PESSOA SET CEP = rtrim(CEP) + ltrim(REPLICATE('0',8-LEN(CEP)))
	WHERE LEN(CEP) != 8
