/** AUTHOR: IGOR **/

--ATUALIZA CLIENTES CNPJ COMPLETANDO CNPJ COM 0 (ZEROS) À ESQUERDA ATÉ QTDE DE DÍGITOS=14:
UPDATE PESSOA SET CNPJ=REPLICATE('0',14-DATALENGTH(CNPJ))+CNPJ WHERE TIPOPESSOA='J' AND DATALENGTH(CNPJ)<14

--ATUALIZA CLIENTES CPF COMPLETANDO CNPJ COM 0 (ZEROS) À ESQUERDA ATÉ QTDE DE DÍGITOS=11:
UPDATE PESSOA SET CNPJ=REPLICATE('0',11-DATALENGTH(CNPJ))+CNPJ WHERE TIPOPESSOA='F' AND DATALENGTH(CNPJ)<11