--DESABILITA TRIGGER [EMPRESA]
USE base_aa;  
GO  
DISABLE TRIGGER ATUALIZA_ULT_NUMCTE_EMPRESA ON EMPRESA;  
GO
DISABLE TRIGGER [ATUALIZA_ULT_NUMNOTA_EMPRESA] ON EMPRESA; 

--ATIVA TRIGGER [EMPRESA]
USE base_aa;  
GO  
ENABLE TRIGGER ATUALIZA_ULT_NUMCTE_EMPRESA ON EMPRESA;  
GO
ENABLE TRIGGER [ATUALIZA_ULT_NUMNOTA_EMPRESA] ON EMPRESA; 