/**
* - @Author: Ruan Alves
* - SQL que recalcula o preço mínimo em cima do perdesconto
*/
UPDATE PRECOTABELA SET 
PRECOMINIMO = ROUND(((PRECOCONSUMIDOR) - ((PRECOCONSUMIDOR) * ((PERDESCONTO)/100))),2), DTULTALTERACAO = GETDATE() 
	WHERE PERDESCONTO IS NOT NULL 
	AND PRECOCONSUMIDOR IS NOT NULL
	AND ISNULL(PRECOCONSUMIDOR,0) > 0
	AND ISNULL(PERDESCONTO, 0) > 0
